title: "Gabriel Cantanhede's Website"
description: "My personal website"
baseurl: "gcantanhede-sci.github.io"
url: "https://gcantanhede-sci.github.io/"
theme: "My theme"

exclude:
  - demo/
  - cvless.gemspec
  - LICENSE
  - README.md
  - screenshot.png

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
